version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: django_pint_field_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./compose/django/.django
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: django_pint_field_local_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    environment:
      - ENGINE=django.db.backends.postgresql_psycopg2
      - POSTGRES_PASSWORD=postgres
      - NAME=postgres
      - USER=postgres
      - PASSWORD=postgres
      - HOST=postgres
      - PORT=5432

