# Generated by Django 4.1.4 on 2022-12-30 19:24

from django.db import migrations, models
import django_pint_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigIntegerPintFieldSaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('weight', django_pint_field.fields.BigIntegerPintField(default_unit='gram', unit_choices=['gram'])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesDefinedInModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_int', django_pint_field.fields.IntegerPintField(default_unit='kilogram', unit_choices=['kilogram', 'milligram', 'pounds'])),
                ('weight_bigint', django_pint_field.fields.BigIntegerPintField(default_unit='kilogram', unit_choices=['kilogram', 'milligram', 'pounds'])),
                ('weight_decimal', django_pint_field.fields.DecimalPintField(decimal_places=2, default_unit='kilogram', max_digits=10, unit_choices=['kilogram', 'milligram', 'pounds'], verbose_name='kilogram')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUregHayBale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_int', django_pint_field.fields.IntegerPintField(default_unit='custom', unit_choices=['custom'])),
                ('custom_bigint', django_pint_field.fields.BigIntegerPintField(default_unit='custom', unit_choices=['custom'])),
                ('custom_decimal', django_pint_field.fields.DecimalPintField(decimal_places=2, default_unit='custom', max_digits=10, unit_choices=['custom'], verbose_name='custom')),
            ],
        ),
        migrations.CreateModel(
            name='DecimalPintFieldSaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('weight', django_pint_field.fields.DecimalPintField(decimal_places=2, default_unit='gram', max_digits=5, unit_choices=['gram'], verbose_name='gram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmptyHayBaleBigInteger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('weight', django_pint_field.fields.BigIntegerPintField(default_unit='gram', null=True, unit_choices=['gram'])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmptyHayBaleDecimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('weight', django_pint_field.fields.DecimalPintField(decimal_places=2, default_unit='gram', max_digits=10, null=True, unit_choices=['gram'], verbose_name='gram')),
                ('compare', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmptyHayBaleInteger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('weight', django_pint_field.fields.IntegerPintField(default_unit='gram', null=True, unit_choices=['gram'])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HayBale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('weight_int', django_pint_field.fields.IntegerPintField(blank=True, default_unit='gram', null=True, unit_choices=['gram'])),
                ('weight_bigint', django_pint_field.fields.BigIntegerPintField(blank=True, default_unit='gram', null=True, unit_choices=['gram'])),
                ('weight_decimal', django_pint_field.fields.DecimalPintField(blank=True, decimal_places=2, default_unit='gram', max_digits=10, null=True, unit_choices=['gram'], verbose_name='gram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegerPintFieldSaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('weight', django_pint_field.fields.IntegerPintField(default_unit='gram', unit_choices=['gram'])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
