# Generated by Django 4.1.4 on 2022-12-28 22:05

from django.db import migrations, models
import django_pint_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dummyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XYZIntFieldSaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('weight', django_pint_field.fields.XYZPintField(default_unit='gram', unit_choices=['gram'])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
