# Generated by Django 4.1.5 on 2023-01-04 17:03

from django.db import migrations, models

import django_pint_field.models


class Migration(migrations.Migration):
    dependencies = [
        ("dummyapp", "0002_defaultsinmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="BigIntegerPintFieldCachedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.BigIntegerPintField(
                        default_unit="gram", unit_choices=["gram"], verbose_name="gram"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DecimalPintFieldCachedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.DecimalPintField(
                        decimal_places=2,
                        default_unit="gram",
                        max_digits=5,
                        unit_choices=["gram"],
                        verbose_name="gram",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntegerPintFieldCachedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.IntegerPintField(
                        default_unit="gram", unit_choices=["gram"], verbose_name="gram"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
