# Generated by Django 4.1.4 on 2022-12-28 22:10

from django.db import migrations
import django_pint_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dummyapp', '0002_xyzintfieldsavemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xyzintfieldsavemodel',
            name='weight',
            field=django_pint_field.fields.XYZPintField(default_unit='gram', unit_choices=['gram', 'pound', 'ounce']),
        ),
    ]
