# Generated by Django 4.1.5 on 2023-01-27 16:31

from django.db import migrations, models
import django_pint_field.models


class Migration(migrations.Migration):
    dependencies = [
        ("dummyapp", "0003_bigintegerpintfieldcachedmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoPintFieldWidgetComparisonModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_int",
                    django_pint_field.models.IntegerPintField(
                        blank=True,
                        default_unit="gram",
                        unit_choices=["gram", "kilogram", "milligram", "pounds"],
                        verbose_name="gram",
                    ),
                ),
                (
                    "weight_bigint",
                    django_pint_field.models.BigIntegerPintField(
                        blank=True,
                        default_unit="gram",
                        unit_choices=["gram", "kilogram", "milligram", "pounds"],
                        verbose_name="gram",
                    ),
                ),
                (
                    "weight_decimal",
                    django_pint_field.models.DecimalPintField(
                        blank=True,
                        decimal_places=2,
                        default_unit="gram",
                        max_digits=10,
                        unit_choices=["gram", "kilogram", "milligram", "pounds"],
                        verbose_name="gram",
                    ),
                ),
                (
                    "tabled_weight_int",
                    django_pint_field.models.IntegerPintField(
                        blank=True,
                        default_unit="gram",
                        unit_choices=["gram", "kilogram", "milligram", "pounds"],
                        verbose_name="gram",
                    ),
                ),
                (
                    "tabled_weight_bigint",
                    django_pint_field.models.BigIntegerPintField(
                        blank=True,
                        default_unit="gram",
                        unit_choices=["gram", "kilogram", "milligram", "pounds"],
                        verbose_name="gram",
                    ),
                ),
                (
                    "tabled_weight_decimal",
                    django_pint_field.models.DecimalPintField(
                        blank=True,
                        decimal_places=2,
                        default_unit="gram",
                        max_digits=10,
                        unit_choices=["gram", "kilogram", "milligram", "pounds"],
                        verbose_name="gram",
                    ),
                ),
            ],
        ),
    ]
