# Generated by Django 5.2.7 on 2025-12-06 02:54

"""Rename the test subject model to experiment subject."""

from django.db import migrations


class Migration(migrations.Migration):
    """Rename the original subject model."""

    dependencies = [
        ("laboratory", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TestSubject",
            new_name="ExperimentSubject",
        ),
    ]
