# Generated by Django 5.1.5 on 2025-01-15 18:12

from decimal import Decimal

from django.db import migrations
from django.db import models

import django_pint_field.indexes
import django_pint_field.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BigIntegerPintFieldCachalotModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.BigIntegerPintField(default_unit="gram", unit_choices=[("gram", "gram")]),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BigIntegerPintFieldCacheopsModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.BigIntegerPintField(default_unit="gram", unit_choices=[("gram", "gram")]),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BigIntegerPintFieldSaveModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.BigIntegerPintField(default_unit="gram", unit_choices=[("gram", "gram")]),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChoicesDefinedInModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "weight_int",
                    django_pint_field.models.IntegerPintField(
                        default_unit="kilogram",
                        unit_choices=[("kilogram", "kilogram"), ("milligram", "milligram"), ("pound", "pound")],
                    ),
                ),
                (
                    "weight_bigint",
                    django_pint_field.models.BigIntegerPintField(
                        default_unit="kilogram",
                        unit_choices=[("kilogram", "kilogram"), ("milligram", "milligram"), ("pound", "pound")],
                    ),
                ),
                (
                    "weight_decimal",
                    django_pint_field.models.DecimalPintField(
                        default_unit="kilogram",
                        display_decimal_places=2,
                        rounding_method=None,
                        unit_choices=[("kilogram", "kilogram"), ("milligram", "milligram"), ("pound", "pound")],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomUregHayBale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "custom_int",
                    django_pint_field.models.IntegerPintField(
                        default_unit="custom", unit_choices=[("custom", "custom")]
                    ),
                ),
                (
                    "custom_bigint",
                    django_pint_field.models.BigIntegerPintField(
                        default_unit="custom", unit_choices=[("custom", "custom")]
                    ),
                ),
                (
                    "custom_decimal",
                    django_pint_field.models.DecimalPintField(
                        default_unit="custom",
                        display_decimal_places=2,
                        rounding_method=None,
                        unit_choices=[("custom", "custom")],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DecimalPintFieldCachalotModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.DecimalPintField(
                        default_unit="gram",
                        display_decimal_places=2,
                        rounding_method=None,
                        unit_choices=[("gram", "gram")],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DecimalPintFieldCacheopsModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.DecimalPintField(
                        default_unit="gram",
                        display_decimal_places=2,
                        rounding_method=None,
                        unit_choices=[("gram", "gram")],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DecimalPintFieldSaveModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.DecimalPintField(
                        default_unit="gram",
                        display_decimal_places=2,
                        rounding_method=None,
                        unit_choices=[("gram", "gram")],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DefaultsInModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight_int",
                    django_pint_field.models.IntegerPintField(
                        blank=True, default=1, default_unit="gram", null=True, unit_choices=[("gram", "gram")]
                    ),
                ),
                (
                    "weight_bigint",
                    django_pint_field.models.BigIntegerPintField(
                        blank=True, default=1, default_unit="gram", null=True, unit_choices=[("gram", "gram")]
                    ),
                ),
                (
                    "weight_decimal",
                    django_pint_field.models.DecimalPintField(
                        blank=True,
                        default=Decimal("1.0"),
                        default_unit="gram",
                        display_decimal_places=2,
                        null=True,
                        rounding_method=None,
                        unit_choices=[("gram", "gram")],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DjangoPintFieldUnitChoicesComparrisonModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "weight_int_list",
                    django_pint_field.models.IntegerPintField(
                        default_unit="gram",
                        unit_choices=[
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("milligram", "milligram"),
                            ("pound", "pound"),
                        ],
                    ),
                ),
                (
                    "weight_int_tuple",
                    django_pint_field.models.IntegerPintField(
                        default_unit="gram",
                        unit_choices=[
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("milligram", "milligram"),
                            ("pound", "pound"),
                        ],
                    ),
                ),
                (
                    "weight_int_nested_list",
                    django_pint_field.models.IntegerPintField(
                        default_unit="gram",
                        unit_choices=[
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("milligram", "milligram"),
                            ("pound", "pound"),
                        ],
                    ),
                ),
                (
                    "weight_int_nested_tuple",
                    django_pint_field.models.IntegerPintField(
                        default_unit="gram",
                        unit_choices=[
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("milligram", "milligram"),
                            ("pound", "pound"),
                        ],
                    ),
                ),
                (
                    "weight_bigint_list",
                    django_pint_field.models.BigIntegerPintField(
                        default_unit="gram",
                        unit_choices=[
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("milligram", "milligram"),
                            ("pound", "pound"),
                        ],
                    ),
                ),
                (
                    "weight_bigint_tuple",
                    django_pint_field.models.BigIntegerPintField(
                        default_unit="gram",
                        unit_choices=[
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("milligram", "milligram"),
                            ("pound", "pound"),
                        ],
                    ),
                ),
                (
                    "weight_bigint_nested_list",
                    django_pint_field.models.BigIntegerPintField(
                        default_unit="gram",
                        unit_choices=[
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("milligram", "milligram"),
                            ("pound", "pound"),
                        ],
                    ),
                ),
                (
                    "weight_bigint_nested_tuple",
                    django_pint_field.models.BigIntegerPintField(
                        default_unit="gram",
                        unit_choices=[
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("milligram", "milligram"),
                            ("pound", "pound"),
                        ],
                    ),
                ),
                (
                    "weight_decimal_list",
                    django_pint_field.models.DecimalPintField(
                        default_unit="gram",
                        display_decimal_places=None,
                        rounding_method=None,
                        unit_choices=[
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("milligram", "milligram"),
                            ("pound", "pound"),
                        ],
                    ),
                ),
                (
                    "weight_decimal_tuple",
                    django_pint_field.models.DecimalPintField(
                        default_unit="gram",
                        display_decimal_places=None,
                        rounding_method=None,
                        unit_choices=[
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("milligram", "milligram"),
                            ("pound", "pound"),
                        ],
                    ),
                ),
                (
                    "weight_decimal_nested_list",
                    django_pint_field.models.DecimalPintField(
                        default_unit="gram",
                        display_decimal_places=None,
                        rounding_method=None,
                        unit_choices=[
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("milligram", "milligram"),
                            ("pound", "pound"),
                        ],
                    ),
                ),
                (
                    "weight_decimal_nested_tuple",
                    django_pint_field.models.DecimalPintField(
                        default_unit="gram",
                        display_decimal_places=None,
                        rounding_method=None,
                        unit_choices=[
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("milligram", "milligram"),
                            ("pound", "pound"),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DjangoPintFieldWidgetComparisonModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "weight_int",
                    django_pint_field.models.IntegerPintField(
                        blank=True,
                        default_unit="gram",
                        null=True,
                        unit_choices=[
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("milligram", "milligram"),
                            ("pound", "pound"),
                        ],
                    ),
                ),
                (
                    "weight_bigint",
                    django_pint_field.models.BigIntegerPintField(
                        blank=True,
                        default_unit="gram",
                        null=True,
                        unit_choices=[
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("milligram", "milligram"),
                            ("pound", "pound"),
                        ],
                    ),
                ),
                (
                    "weight_decimal",
                    django_pint_field.models.DecimalPintField(
                        blank=True,
                        default_unit="gram",
                        display_decimal_places=2,
                        null=True,
                        rounding_method=None,
                        unit_choices=[
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("milligram", "milligram"),
                            ("pound", "pound"),
                        ],
                    ),
                ),
                (
                    "tabled_weight_int",
                    django_pint_field.models.IntegerPintField(
                        blank=True,
                        default_unit="gram",
                        null=True,
                        unit_choices=[
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("milligram", "milligram"),
                            ("pound", "pound"),
                        ],
                    ),
                ),
                (
                    "tabled_weight_bigint",
                    django_pint_field.models.BigIntegerPintField(
                        blank=True,
                        default_unit="gram",
                        null=True,
                        unit_choices=[
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("milligram", "milligram"),
                            ("pound", "pound"),
                        ],
                    ),
                ),
                (
                    "tabled_weight_decimal",
                    django_pint_field.models.DecimalPintField(
                        blank=True,
                        default_unit="gram",
                        display_decimal_places=2,
                        null=True,
                        rounding_method=None,
                        unit_choices=[
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("milligram", "milligram"),
                            ("pound", "pound"),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmptyHayBaleBigInteger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.BigIntegerPintField(
                        default_unit="gram", null=True, unit_choices=[("gram", "gram")]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmptyHayBaleDecimal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.DecimalPintField(
                        default_unit="gram",
                        display_decimal_places=2,
                        null=True,
                        rounding_method=None,
                        unit_choices=[("gram", "gram")],
                    ),
                ),
                ("compare", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmptyHayBaleInteger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.IntegerPintField(
                        default_unit="gram", null=True, unit_choices=[("gram", "gram")]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HayBale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight_int",
                    django_pint_field.models.IntegerPintField(
                        blank=True, default_unit="gram", null=True, unit_choices=[("gram", "gram")]
                    ),
                ),
                (
                    "weight_bigint",
                    django_pint_field.models.BigIntegerPintField(
                        blank=True, default_unit="gram", null=True, unit_choices=[("gram", "gram")]
                    ),
                ),
                (
                    "weight_decimal",
                    django_pint_field.models.DecimalPintField(
                        blank=True,
                        default_unit="gram",
                        display_decimal_places=2,
                        null=True,
                        rounding_method=None,
                        unit_choices=[("gram", "gram")],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntegerPintFieldCachalotModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.IntegerPintField(default_unit="gram", unit_choices=[("gram", "gram")]),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntegerPintFieldCachopsModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.IntegerPintField(default_unit="gram", unit_choices=[("gram", "gram")]),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntegerPintFieldSaveModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.IntegerPintField(default_unit="gram", unit_choices=[("gram", "gram")]),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntegerPintFieldSaveWithIndexModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.IntegerPintField(default_unit="gram", unit_choices=[("gram", "gram")]),
                ),
                (
                    "weight_two",
                    django_pint_field.models.IntegerPintField(
                        default_unit="kilogram", unit_choices=[("kilogram", "kilogram")]
                    ),
                ),
            ],
            options={
                "indexes": [
                    django_pint_field.indexes.PintFieldComparatorIndex(
                        condition=None,
                        db_tablespace=None,
                        fields=["weight"],
                        include=(),
                        name="weight_idx",
                        opclasses=(),
                    ),
                    django_pint_field.indexes.PintFieldComparatorIndex(
                        condition=None,
                        db_tablespace=None,
                        fields=["weight", "weight_two"],
                        include=(),
                        name="weight_weight_two_idx",
                        opclasses=(),
                    ),
                ],
            },
        ),
    ]
