"""First migration for the example app."""

# Generated by Django 5.1.2 on 2024-11-04 17:08

from decimal import Decimal

from django.db import migrations
from django.db import models

import django_pint_field.models


class Migration(migrations.Migration):
    """First migration for the example app."""

    initial = True

    dependencies = [("django_pint_field", "0002_consolidate_composite_fields")]

    operations = [
        migrations.CreateModel(
            name="BigIntegerPintFieldCachedModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                ("weight", django_pint_field.models.BigIntegerPintField(default_unit="gram", unit_choices=["gram"])),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BigIntegerPintFieldSaveModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                ("weight", django_pint_field.models.BigIntegerPintField(default_unit="gram", unit_choices=["gram"])),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChoicesDefinedInModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "weight_int",
                    django_pint_field.models.IntegerPintField(
                        default_unit="kilogram", unit_choices=["kilogram", "milligram", "pounds"]
                    ),
                ),
                (
                    "weight_bigint",
                    django_pint_field.models.BigIntegerPintField(
                        default_unit="kilogram", unit_choices=["kilogram", "milligram", "pounds"]
                    ),
                ),
                (
                    "weight_decimal",
                    django_pint_field.models.DecimalPintField(
                        decimal_places=2,
                        default_unit="kilogram",
                        max_digits=10,
                        unit_choices=["kilogram", "milligram", "pounds"],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomUregHayBale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "custom_int",
                    django_pint_field.models.IntegerPintField(default_unit="custom", unit_choices=["custom"]),
                ),
                (
                    "custom_bigint",
                    django_pint_field.models.BigIntegerPintField(default_unit="custom", unit_choices=["custom"]),
                ),
                (
                    "custom_decimal",
                    django_pint_field.models.DecimalPintField(
                        decimal_places=2, default_unit="custom", max_digits=10, unit_choices=["custom"]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DecimalPintFieldCachedModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.DecimalPintField(
                        decimal_places=2, default_unit="gram", max_digits=5, unit_choices=["gram"]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DecimalPintFieldSaveModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.DecimalPintField(
                        decimal_places=2, default_unit="gram", max_digits=5, unit_choices=["gram"]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DefaultsInModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight_int",
                    django_pint_field.models.IntegerPintField(
                        blank=True, default=1, default_unit="gram", null=True, unit_choices=["gram"]
                    ),
                ),
                (
                    "weight_bigint",
                    django_pint_field.models.BigIntegerPintField(
                        blank=True, default=1, default_unit="gram", null=True, unit_choices=["gram"]
                    ),
                ),
                (
                    "weight_decimal",
                    django_pint_field.models.DecimalPintField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("1.0"),
                        default_unit="gram",
                        max_digits=10,
                        null=True,
                        unit_choices=["gram"],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DjangoPintFieldWidgetComparisonModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "weight_int",
                    django_pint_field.models.IntegerPintField(
                        blank=True,
                        default_unit="gram",
                        null=True,
                        unit_choices=["gram", "kilogram", "milligram", "pounds"],
                    ),
                ),
                (
                    "weight_bigint",
                    django_pint_field.models.BigIntegerPintField(
                        blank=True,
                        default_unit="gram",
                        null=True,
                        unit_choices=["gram", "kilogram", "milligram", "pounds"],
                    ),
                ),
                (
                    "weight_decimal",
                    django_pint_field.models.DecimalPintField(
                        blank=True,
                        decimal_places=2,
                        default_unit="gram",
                        max_digits=10,
                        null=True,
                        unit_choices=["gram", "kilogram", "milligram", "pounds"],
                    ),
                ),
                (
                    "tabled_weight_int",
                    django_pint_field.models.IntegerPintField(
                        blank=True,
                        default_unit="gram",
                        null=True,
                        unit_choices=["gram", "kilogram", "milligram", "pounds"],
                    ),
                ),
                (
                    "tabled_weight_bigint",
                    django_pint_field.models.BigIntegerPintField(
                        blank=True,
                        default_unit="gram",
                        null=True,
                        unit_choices=["gram", "kilogram", "milligram", "pounds"],
                    ),
                ),
                (
                    "tabled_weight_decimal",
                    django_pint_field.models.DecimalPintField(
                        blank=True,
                        decimal_places=2,
                        default_unit="gram",
                        max_digits=10,
                        null=True,
                        unit_choices=["gram", "kilogram", "milligram", "pounds"],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmptyHayBaleBigInteger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.BigIntegerPintField(default_unit="gram", null=True, unit_choices=["gram"]),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmptyHayBaleDecimal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.DecimalPintField(
                        decimal_places=2, default_unit="gram", max_digits=10, null=True, unit_choices=["gram"]
                    ),
                ),
                ("compare", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmptyHayBaleInteger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight",
                    django_pint_field.models.IntegerPintField(default_unit="gram", null=True, unit_choices=["gram"]),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HayBale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "weight_int",
                    django_pint_field.models.IntegerPintField(
                        blank=True, default_unit="gram", null=True, unit_choices=["gram"]
                    ),
                ),
                (
                    "weight_bigint",
                    django_pint_field.models.BigIntegerPintField(
                        blank=True, default_unit="gram", null=True, unit_choices=["gram"]
                    ),
                ),
                (
                    "weight_decimal",
                    django_pint_field.models.DecimalPintField(
                        blank=True,
                        decimal_places=2,
                        default_unit="gram",
                        max_digits=10,
                        null=True,
                        unit_choices=["gram"],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntegerPintFieldCachedModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                ("weight", django_pint_field.models.IntegerPintField(default_unit="gram", unit_choices=["gram"])),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntegerPintFieldSaveModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                ("weight", django_pint_field.models.IntegerPintField(default_unit="gram", unit_choices=["gram"])),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
