# Generated by Django 5.2.7 on 2025-10-26 21:16

import django_pint_field.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PintFieldWithCheckConstraint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                (
                    "min_weight",
                    django_pint_field.models.DecimalPintField(
                        default=Decimal("0.0"),
                        default_unit="gram",
                        display_decimal_places=2,
                        rounding_method=None,
                        unit_choices=[("gram", "gram")],
                    ),
                ),
                (
                    "max_weight",
                    django_pint_field.models.DecimalPintField(
                        default=Decimal("1000.0"),
                        default_unit="gram",
                        display_decimal_places=2,
                        rounding_method=None,
                        unit_choices=[("gram", "gram")],
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("min_weight__lte", models.F("max_weight"))),
                        name="min_weight_lte_max_weight",
                    )
                ],
            },
        ),
    ]
