# Generated by Django 5.2.12 on 2026-05-23 23:22

"""Add the TemperatureReadingModel to the example app."""

import django_pint_field.models
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create the TemperatureReadingModel table."""

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemperatureReadingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "temperature",
                    django_pint_field.models.DecimalPintField(
                        default_unit="kelvin",
                        display_decimal_places=None,
                        rounding_method=None,
                        unit_choices=[
                            ("kelvin", "kelvin"),
                            ("°C", "degC"),
                            ("°F", "degF"),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
