"""Second migration for the example app."""

# Generated by Django 5.1.2 on 2024-11-08 22:15

from django.db import migrations
from django.db import models

import django_pint_field.indexes
import django_pint_field.models


class Migration(migrations.Migration):
    """Second migration for the example app."""

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegerPintFieldSaveWithIndexModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                ("weight", django_pint_field.models.IntegerPintField(default_unit="gram", unit_choices=["gram"])),
                (
                    "weight_two",
                    django_pint_field.models.IntegerPintField(default_unit="kilogram", unit_choices=["kilogram"]),
                ),
            ],
            options={
                "indexes": [
                    django_pint_field.indexes.PintFieldComparatorIndex(
                        condition=None,
                        db_tablespace=None,
                        fields=["weight"],
                        include=(),
                        name="weight_idx",
                        opclasses=(),
                    ),
                    django_pint_field.indexes.PintFieldComparatorIndex(
                        condition=None,
                        db_tablespace=None,
                        fields=["weight", "weight_two"],
                        include=(),
                        name="weight_weight_two_idx",
                        opclasses=(),
                    ),
                ],
            },
        ),
    ]
